# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "eli_ez3r Story"
description: > # this means to ignore newlines until "email:"
   eli_ez3r blog

email: 0.0eli.ez3r@gmail.com

#blog logo
logo: "/assets/images/dragonfly_moon.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'eli_ez3r'
author: 'eli_ez3r'
author_image: "/assets/images/eli_ez3r_circle.jpg"

paginate:	5

url: "https://eli_ez3r.github.io" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
disqus: eli_ez3r-blog

#google_analytics: UA-91026007-2

# social icons and sharing options
social:
  - icon:	twitter
    url:	#https://twitter.com/dirkfabisch
    desc: #Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	#https://facebook.com/???
    desc: #Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dreamgonfly
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

markdown: kramdown
